### ISSUE TITLE
creds search: document fields used by keyword searches

### ISSUE THREAD

**Issue by mkjones-oai** [Flared/docs-api#22]
Path: /api-reference/leaksdb/endpoints/post-credentials-search

I see that I can query with domain, password, or "keyword", but I don't know what fields "keyword" actually searches.  It would be great to document that here.

**Comment by aviau** [comment]
Thanks for the report @mkjones-oai.

I just released an update. What do you think?
- https://api.docs.flare.io/api-reference/leaksdb/endpoints/post-credentials-search

<img width="606" alt="Screenshot 2024-10-18 at 12 50 27 PM" src="https://github.com/user-attachments/assets/fe2e0a9d-f2a8-47d5-bc78-bbc1a0cd79a9">

**Comment by mkjones-oai** [comment]
Great, thanks! I assume username is the same as "identity_name" as shown on the response? If so, it might be good to call it that.
<img width="464" alt="image" src="https://github.com/user-attachments/assets/8887ba01-cabf-4121-b8c6-0ab7ed0e34bf">

**Comment by aviau** [comment]
Not really. Its only the username part of the identity_name. I can add details.
