### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by klara-cph-soc** [Flared/docs-api#40]
Path: /api-reference/v2/endpoints/activities/get-activities

there is no guide or explanation on what these parameters are supposed to be. Making it difficult to  build a call based on such minimal data. 

Is it possible to add explanations and potential parameter examples?

**Comment by aviau** [comment]
We added more info on this page:
- https://api.docs.flare.io/api-reference/v2/endpoints/activities/get-activities

Let us know what you think.
